#!/bin/bash

if [ "$1" -eq 1 ]; then
  cmake -DVTKm_DIR=../serial/lib/cmake/vtkm-1.1 -DCMAKE_BUILD_TYPE=Release
elif [ "$1" -eq 2 ]; then
  cmake -DVTKm_DIR=../tbb/lib/cmake/vtkm-1.1 -DCMAKE_BUILD_TYPE=Release
else
  cmake -DVTKm_DIR=../cuda/lib/cmake/vtkm-1.1 -DCMAKE_BUILD_TYPE=Release
fi
